image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      export CYPRESS_CACHE_FOLDER=/workspace/.cypress-cache
      npm install
      gp sync-done install
    command: npm run dev
  - init: gp sync-await install
    command: npm run cy:open
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore
